
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.dj;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sun Apr 21 17:37:43 IST 2013
 * Generated source version: 2.2.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuthenticateService",
                      portName = "AuthenticateServiceSOAP",
                      targetNamespace = "http://www.dj.com/AuthenticateService/",
                      wsdlLocation = "http://www.dj.com/?wsdl",
                      endpointInterface = "com.dj.AuthenticateService")
                      
public class AuthenticateServiceImpl implements AuthenticateService {

    private static final Logger LOG = Logger.getLogger(AuthenticateServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.dj.AuthenticateService#authenticate(com.dj.AuthenticateRequest  parameters )*
     */
    public com.dj.AuthenticateResponse authenticate(AuthenticateRequest parameters) { 
        LOG.info("Executing operation authenticate");
        System.out.println(parameters);
        com.dj.AuthenticateResponse response = new com.dj.AuthenticateResponse();
        try {
            
            if(parameters.getUsername().equalsIgnoreCase("deepujs") 
        			&& parameters.getPassword().equals("ambilycr")){
            	response.setStatus(true);
        	}else{
        		response.setStatus(false);
        	}
        } catch (Exception ex) {
            ex.printStackTrace();
            response.setStatus(false);
        }
        return response;
    }

}
