
package com.dj;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sun Apr 21 17:37:44 IST 2013
 * Generated source version: 2.2.9
 * 
 */
 
public class AuthenticateService_AuthenticateServiceSOAP_Server{

    protected AuthenticateService_AuthenticateServiceSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new AuthenticateServiceImpl();
        String address = "http://www.dj.com/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new AuthenticateService_AuthenticateServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
